# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
       python-version: '3.7'  
   
    #- name: set ndk
      #run: echo "::set-env name=ANDROID_NDK_ROOT::$ANDROID_SDK_ROOT/ndk-bundle"

    # Runs a set of commands using the runners shell
    - name: make frida-server for arm
      run: |
       sudo apt-get install tree wget curl ninja-build -y
       sudo apt-get install build-essential gcc-multilib lib32stdc++-5-dev git -y
       sudo apt-get install flex bison -y
       curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
       sudo apt-get install -y nodejs
        
       #git clone https://github.com/frida/frida
       #cd frida
        
       #sed -i 's/git:/https:/g' .gitmodules 
        
       #git submodule update --init --recursive
        
       #echo git submodule update result $?
        
       #make --debug=vvv
        
       wget https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip
       unzip -q android-ndk-r21-linux-x86_64.zip
        
       ANDROID_NDK_ROOT=$(pwd)/android-ndk-r21
        
       make build/frida-android-arm/lib/pkgconfig/frida-core-1.0.pc --debug=vvv -j4

    - name: check
      run: |
       file frida/build/frida-android-arm/bin/frida-server
